stages:
  - build
  - test
  - deploy
  
cache:
  paths:
    - target/
  
build:
  stage: build
  tags:
    - maven
  script:
    - echo "Building project with maven"
    - mvn clean package
  artifacts:
    paths:
      - target/transportpipes-**.jar
deploy:
  stage: deploy
  tags:
    - maven
  script:
    - echo "Deploying project with maven"
    - mvn deploy
