name: TransportPipes
version: ${project.version}
author: RoboTricker
main: de.robotricker.transportpipes.TransportPipes
load: STARTUP
depend: [ProtocolLib]
loadbefore: [ProtocolLib, AuthMe]
commands:
  transportpipes:
    aliases: [transportpipe, tpipes, tpipe, pipes, pipe]
