name: TransportPipes
version: ${project.version}
author: RoboTricker
main: de.robotricker.transportpipes.TransportPipes
load: STARTUP
depend: [ProtocolLib]
commands:
  transportpipessettings:
    aliases: [tpsettings]
  transportpipestps:
    aliases: [tptps]
  tt:
