name: TransportPipes
version: ${project.versionCode}
author: RoboTricker
main: de.robotricker.transportpipes.TransportPipes
load: STARTUP
depend: [ProtocolLib]
softdepend: [LogisticsAPI]
loadbefore: [ProtocolLib, AuthMe, LogisticsAPI]
commands:
  transportpipes:
    aliases: [transportpipe, tpipes, tpipe, pipes, pipe]
