name: TransportPipes
version: 3.5.0
author: RoboTricker
main: de.robotricker.transportpipes.TransportPipes
load: STARTUP
depend: [ProtocolLib]
commands:
  transportpipessettings:
    aliases: [tpsettings]
  transportpipestps:
    aliases: [tptps]